### PR TITLE
feature:S3C-3575 pass spring config file by mounting

### PR DESCRIPTION
**Pull request by saitharunthodupunuru**

### CODE REVIEW

**Review by anurag4DSB — COMMENTED** [review]
How will the instructions in other readme for running docker image change(if any)

**Comment by saitharunthodupunuru** [comment]
> How will the instructions in other readme for running docker image change(if any)

Totally Missed the Readme part. Thanks
Added it in f21d9e017bc51ae997ba800b914c6feaa9d09ec8

**Review by anurag4DSB — APPROVED** [review]

**Review by naren-scality — APPROVED** [review]

**Pull request merged**
