### PR TITLE
feature: OSIS-72 remove fail_ci_if_error flag for codecov

### PR DESCRIPTION
**Pull request by XinLiScality**

### CODE REVIEW

**Review by anurag4DSB — APPROVED** [review]

**Comment by XinLiScality** [comment]
help

**Comment by miniscruff** [comment]
Is codecov failing often for us to remove this check?

**Comment by XinLiScality** [comment]
> Is codecov failing often for us to remove this check? Edit: Also the issue linked does not seem at all the same as the change in the PR.

yeah codecov is falling for 0.02% decrease in one of our PR https://github.com/scality/osis/pull/93 with only one line removed https://app.codecov.io/gh/scality/osis/compare/93/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr%20comments&utm_term=scality#diff-b3Npcy1jb3JlL3NyYy9tYWluL2phdmEvY29tL3NjYWxpdHkvb3Npcy91dGlscy9TY2FsaXR5TW9kZWxDb252ZXJ0ZXIuamF2YQ==

**Review by WillToozsScality — APPROVED** [review]

**Pull request merged**
