### PR TITLE
feature:OSIS-23 implement Delete User

### PR DESCRIPTION
**Pull request by saitharunthodupunuru**
Description: 
1. Detach User policy attached with user 
2. Delete IAM user

### CODE REVIEW

**Review by anurag4DSB — APPROVED** [review]

**Review by RachedBenMustapha — APPROVED** [review]
Not specific to this PR but `ScalityOsisServiceImpl.deleteUser` and similar methods don't really convey success/failure status back to the caller, how does the caller know there was an error?

**Comment by saitharunthodupunuru** [comment]
> Not specific to this PR but `ScalityOsisServiceImpl.deleteUser` and similar methods don't really convey success/failure status back to the caller, how does the caller know there was an error?

Hey @RachedBenMustapha 
`ScalityOsisController.java` provides all the API definitions and only kinds of responses for each API.
Same information is available on this Swagger doc https://code.vmware.com/apis/1034#/

OSIS returns only the provided errors if not we have the AWS exceptions like `NoSuchEntityException`, `LimitExceededException`, `ServiceFailureException`, etc

**Pull request merged**
